"""Pure code generator for the Memthick tab — no Dash, no IO.

The Memthick tab is a *configure → generate code → run elsewhere* workflow:
the user picks parameters in the form, then hands a ``.py`` / ``.ipynb`` /
SLURM script off to a cluster login node. This module is the seam where form
state becomes runnable code.

Keeping it Dash-free makes it trivial to unit-test (string snapshots) and
means the generated code does not depend on importing any of ``cryocat.app``.

The notebook structure mirrors ``docs/source/tutorials/membrane_thickness/
memthick_run.ipynb``: title → imports → path variables → membrane labels →
analyzer → run.

Public API
----------
* :func:`render_pipeline_py(kwargs)`        -> ``str``
* :func:`render_pipeline_ipynb(kwargs)`     -> ``dict`` (nb v4)
* :func:`render_pipeline_ipynb_json(kwargs)`-> ``str`` (JSON-encoded notebook)
* :func:`render_slurm_wrapper`              -> re-exported from
  :mod:`cryocat.app.suite.pages._codegen_base`
"""
from __future__ import annotations

import json
from typing import Any

from cryocat.app.suite.pages._codegen_base import (
    Verbatim as _Verbatim,
    format_value as _format_value,
    format_dict as _format_dict,
    format_kwargs as _format_kwargs,
    render_slurm_wrapper,  # noqa: F401 — re-exported for callers
    code_cell,
    markdown_cell,
    notebook,
)


_PIPELINE_FN = "run_full_pipeline"
_ANALYZER_CLS = "IntensityProfileAnalyzer"

# Path params lifted to named variables at the top of the script so the
# user can edit cluster paths in one obvious place.
_PATH_PARAMS: dict[str, str] = {
    "segmentation_map": "segmentation_path",
    "output_path": "output_path",
    "tomogram_map": "tomogram_path",
}


# ── kwargs splitting ────────────────────────────────────────────────────────


def _split_kwargs(kwargs: dict[str, Any]) -> tuple[dict, dict, dict, dict]:
    """Partition the assembled kwargs into rendering buckets.

    Returns
    -------
    paths : dict[var_name, value]
        Path params extracted from ``kwargs`` (in the order defined by
        :data:`_PATH_PARAMS`).
    labels : dict or None
        ``membrane_labels`` if present; rendered as a standalone dict
        literal so the user can edit it without scrolling.
    analyzer_kwargs : dict or None
        :class:`IntensityProfileAnalyzer` constructor kwargs (kept under
        ``kwargs["analyzer"]`` by the page).
    call_kwargs : dict
        Everything left -- the kwargs passed to ``run_full_pipeline``.
    """
    paths: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if kwarg_name in kwargs:
            paths[var_name] = kwargs[kwarg_name]
    labels = kwargs.get("membrane_labels")
    analyzer_kwargs = kwargs.get("analyzer") if isinstance(kwargs.get("analyzer"), dict) else None
    skip = set(_PATH_PARAMS) | {"membrane_labels", "analyzer"}
    call_kwargs = {k: v for k, v in kwargs.items() if k not in skip}
    return paths, labels, analyzer_kwargs, call_kwargs


# ── .py renderer ────────────────────────────────────────────────────────────


def render_pipeline_py(kwargs: dict[str, Any]) -> str:
    """Render a runnable ``.py`` script for the configured pipeline.

    Sections mirror the notebook structure:

    1. Module docstring + ``from cryocat.analysis import memthick``.
    2. Path variables hoisted to the top (``segmentation_path``,
       ``output_path``, ``tomogram_path`` when set).
    3. ``membrane_labels`` dict literal.
    4. ``analyzer = memthick.IntensityProfileAnalyzer(...)`` (omitted when
       the form left the analyzer at its defaults).
    5. ``results = memthick.run_full_pipeline(...)``.

    Parameters
    ----------
    kwargs : dict
        Combined form state. Pass ``kwargs["analyzer"]`` (a dict of
        :class:`IntensityProfileAnalyzer` kwargs) when the user filled the
        analyzer sub-form.
    """
    paths, labels, analyzer_kwargs, call_kwargs = _split_kwargs(kwargs)

    lines: list[str] = [
        '"""Auto-generated by the cryoCAT membrane-thickness tab. Edit freely."""',
        "from cryocat.analysis import memthick",
        "",
    ]

    # ── path variables ─────────────────────────────────────────────────────
    if paths:
        for var_name, value in paths.items():
            lines.append(f"{var_name} = {_format_value(value)}")
        lines.append("")

    # ── membrane labels ────────────────────────────────────────────────────
    if labels:
        lines.append(f"membrane_labels = {_format_dict(labels, indent='')}")
        lines.append("")

    # ── analyzer ───────────────────────────────────────────────────────────
    if analyzer_kwargs:
        lines.append(f"analyzer = memthick.{_ANALYZER_CLS}(")
        lines.append(_format_kwargs(analyzer_kwargs, indent="    "))
        lines.append(")")
        lines.append("")

    # ── pipeline call ──────────────────────────────────────────────────────
    referenced_call_kwargs: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if var_name in paths:
            referenced_call_kwargs[kwarg_name] = _Verbatim(var_name)
    if labels:
        referenced_call_kwargs["membrane_labels"] = _Verbatim("membrane_labels")
    referenced_call_kwargs.update(call_kwargs)
    if analyzer_kwargs:
        referenced_call_kwargs["analyzer"] = _Verbatim("analyzer")

    lines.append(f"results = memthick.{_PIPELINE_FN}(")
    lines.append(_format_kwargs(referenced_call_kwargs, indent="    "))
    lines.append(")")
    lines.append("")
    lines.append('print("done:", results)')
    lines.append("")
    return "\n".join(lines)


# ── .ipynb renderer ─────────────────────────────────────────────────────────


def render_pipeline_ipynb(kwargs: dict[str, Any]) -> dict:
    """Render an ``nbformat`` v4 notebook dict.

    Cells follow the source notebook
    (``memthick_run.ipynb``): title → imports → path variables →
    ``membrane_labels`` → analyzer → run.

    Returned as a plain dict so the page (or a test) can ``json.dumps`` it
    without an ``nbformat`` dependency.
    """
    paths, labels, analyzer_kwargs, call_kwargs = _split_kwargs(kwargs)

    cells: list[dict] = []
    cells.append(markdown_cell(
        "# Running the membrane thickness estimation pipeline\n"
        "\n"
        "Auto-generated by the cryoCAT membrane-thickness tab. Edit freely.\n"
    ))
    cells.append(code_cell("from cryocat.analysis import memthick\n"))

    if paths:
        path_lines = "\n".join(
            f"{var_name} = {_format_value(value)}"
            for var_name, value in paths.items()
        ) + "\n"
        cells.append(code_cell(path_lines))

    if labels:
        cells.append(code_cell(f"membrane_labels = {_format_dict(labels, indent='')}\n"))

    if analyzer_kwargs:
        cells.append(code_cell(
            f"analyzer = memthick.{_ANALYZER_CLS}(\n"
            + _format_kwargs(analyzer_kwargs, indent="    ") + "\n"
            + ")\n"
        ))

    referenced_call_kwargs: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if var_name in paths:
            referenced_call_kwargs[kwarg_name] = _Verbatim(var_name)
    if labels:
        referenced_call_kwargs["membrane_labels"] = _Verbatim("membrane_labels")
    referenced_call_kwargs.update(call_kwargs)
    if analyzer_kwargs:
        referenced_call_kwargs["analyzer"] = _Verbatim("analyzer")

    cells.append(code_cell(
        f"results = memthick.{_PIPELINE_FN}(\n"
        + _format_kwargs(referenced_call_kwargs, indent="    ") + "\n"
        + ")\n"
        + "results\n"
    ))

    return notebook(cells)


def render_pipeline_ipynb_json(kwargs: dict[str, Any]) -> str:
    """:func:`render_pipeline_ipynb` then ``json.dumps`` with stable indent."""
    return json.dumps(render_pipeline_ipynb(kwargs), indent=1)
