"""Pure code generator for the Peak Analysis (pana) tab — no Dash, no IO.

The pana tab uses a *configure → generate code → run elsewhere* workflow for
batch runs: the user fills in the CSV template list path and options, then
hands a ``.py`` / SLURM script to a cluster login node. This module is the
seam where form state becomes runnable code.

Keeping it Dash-free makes it trivial to unit-test (string snapshots) and
means the generated code does not depend on importing any of
``cryocat.app``.

Public API
----------
* :func:`render_analysis_py(kwargs)`  -> ``str``
* :func:`render_slurm_wrapper`        -> re-exported from
  :mod:`cryocat.app.suite.pages._codegen_base`
"""
from __future__ import annotations

from typing import Any

from cryocat.app.suite.pages._codegen_base import (
    Verbatim as _Verbatim,
    format_value as _format_value,
    format_kwargs as _format_kwargs,
    render_slurm_wrapper,  # noqa: F401 — re-exported for callers
)


# Path params hoisted to named variables at the top of the generated script.
_PATH_PARAMS: dict[str, str] = {
    "template_list":      "template_list",
    "parent_folder_path": "parent_folder_path",
    "angle_list_path":    "angle_list_path",
    "wedge_path":         "wedge_path",
}


# ── .py renderer ────────────────────────────────────────────────────────────


def render_analysis_py(kwargs: dict[str, Any]) -> str:
    """Render a runnable ``.py`` script calling :func:`pana.run_analysis`.

    Path parameters (``template_list``, ``parent_folder_path``,
    ``angle_list_path``, ``wedge_path``) are hoisted to named variables at
    the top so the user can edit cluster paths in one obvious place.

    Parameters
    ----------
    kwargs : dict
        Form state to forward to ``pana.run_analysis``.  Any key present in
        :data:`_PATH_PARAMS` becomes a top-level variable; everything else is
        inlined as a keyword argument.
    """
    paths: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if kwargs.get(kwarg_name) is not None:
            paths[var_name] = kwargs[kwarg_name]

    skip = set(_PATH_PARAMS)
    call_kwargs: dict[str, Any] = {k: v for k, v in kwargs.items()
                                    if k not in skip and v is not None}

    lines: list[str] = [
        '"""Auto-generated by the cryoCAT peak-analysis tab. Edit freely."""',
        "from cryocat.analysis import pana",
        "",
    ]

    if paths:
        for var_name, value in paths.items():
            lines.append(f"{var_name} = {_format_value(value)}")
        lines.append("")

    referenced: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if var_name in paths:
            referenced[kwarg_name] = _Verbatim(var_name)
    referenced.update(call_kwargs)

    lines.append("pana.run_analysis(")
    lines.append(_format_kwargs(referenced, indent="    "))
    lines.append(")")
    lines.append("")
    lines.append('print("done")')
    lines.append("")
    return "\n".join(lines)
