"""Pure code generator for the Peak Analysis (pana) tab — no Dash, no IO.

The pana tab uses a *configure → generate code → run elsewhere* workflow for
batch runs: the user fills in the CSV template list path and options, then
hands a ``.py`` / SLURM script to a cluster login node. This module is the
seam where form state becomes runnable code.

Keeping it Dash-free makes it trivial to unit-test (string snapshots) and
means the generated code does not depend on importing any of
``cryocat.app``.

Public API
----------
* :func:`render_analysis_py(kwargs)`  -> ``str``
* :func:`render_slurm_wrapper(py_filename, cluster_params, module_loads)` -> ``str``
"""
from __future__ import annotations

import io
from typing import Any


# Path params hoisted to named variables at the top of the generated script.
_PATH_PARAMS: dict[str, str] = {
    "template_list":     "template_list",
    "parent_folder_path": "parent_folder_path",
    "angle_list_path":   "angle_list_path",
    "wedge_path":        "wedge_path",
}


# ── value formatters ────────────────────────────────────────────────────────


def _format_value(value: Any) -> str:
    """Return a Python source representation of *value*."""
    if isinstance(value, _Verbatim):
        return value.expr
    return repr(value)


class _Verbatim:
    """Marker so :func:`_format_value` emits a bare identifier."""

    __slots__ = ("expr",)

    def __init__(self, expr: str) -> None:
        self.expr = expr


def _format_kwargs(kwargs: dict[str, Any], indent: str = "    ") -> str:
    if not kwargs:
        return ""
    return "\n".join(
        f"{indent}{name}={_format_value(value)}," for name, value in kwargs.items()
    )


# ── .py renderer ────────────────────────────────────────────────────────────


def render_analysis_py(kwargs: dict[str, Any]) -> str:
    """Render a runnable ``.py`` script calling :func:`pana.run_analysis`.

    Path parameters (``template_list``, ``parent_folder_path``,
    ``angle_list_path``, ``wedge_path``) are hoisted to named variables at
    the top so the user can edit cluster paths in one obvious place.

    Parameters
    ----------
    kwargs : dict
        Form state to forward to ``pana.run_analysis``.  Any key present in
        :data:`_PATH_PARAMS` becomes a top-level variable; everything else is
        inlined as a keyword argument.
    """
    # Split path params from scalar params
    paths: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if kwargs.get(kwarg_name) is not None:
            paths[var_name] = kwargs[kwarg_name]

    skip = set(_PATH_PARAMS)
    call_kwargs: dict[str, Any] = {k: v for k, v in kwargs.items()
                                    if k not in skip and v is not None}

    lines: list[str] = [
        '"""Auto-generated by the cryoCAT peak-analysis tab. Edit freely."""',
        "from cryocat.analysis import pana",
        "",
    ]

    # ── path variables ─────────────────────────────────────────────────────
    if paths:
        for var_name, value in paths.items():
            lines.append(f"{var_name} = {_format_value(value)}")
        lines.append("")

    # ── run_analysis call ──────────────────────────────────────────────────
    referenced: dict[str, Any] = {}
    for kwarg_name, var_name in _PATH_PARAMS.items():
        if var_name in paths:
            referenced[kwarg_name] = _Verbatim(var_name)
    referenced.update(call_kwargs)

    lines.append("pana.run_analysis(")
    lines.append(_format_kwargs(referenced, indent="    "))
    lines.append(")")
    lines.append("")
    lines.append('print("done")')
    lines.append("")
    return "\n".join(lines)


# ── SLURM wrapper ───────────────────────────────────────────────────────────


def render_slurm_wrapper(
    py_filename: str,
    cluster_params: dict | None = None,
    module_loads: list[str] | None = None,
    interpreter: str = "#!/bin/bash",
) -> str:
    """Wrap a generated ``.py`` script in a SLURM submission script.

    Parameters
    ----------
    py_filename : str
        Path the cluster will see for the generated python script.
    cluster_params : dict, optional
        SBATCH parameters. Keys starting with ``--`` produce
        ``#SBATCH --key=value``; keys starting with ``-`` produce
        ``#SBATCH -key value``.
    module_loads : list of str, optional
        ``module load`` directives.
    interpreter : str
        Shebang line.
    """
    from cryocat.utils.scriptutils import process_cluster_params

    buf = io.StringIO()
    buf.write(interpreter + "\n")
    if cluster_params:
        process_cluster_params(buf, cluster_params)
    for mod in module_loads or []:
        buf.write(f"module load {mod}\n")
    buf.write(f"python {py_filename}\n")
    return buf.getvalue()


def _parse_sbatch_text(text: str) -> dict:
    """Parse newline-separated SBATCH directive lines into a kwargs dict."""
    result: dict[str, Any] = {}
    for line in (text or "").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            result[k.strip()] = v.strip()
        else:
            parts = line.split(None, 1)
            result[parts[0]] = parts[1] if len(parts) > 1 else ""
    return result
